FTSE_100 = [['ADN', 'Aberdeen Asset Management'],
            ['ADM', 'Admiral Group'],
            ['AGK', 'Aggreko'],
            ['AMEC', 'Amec'],
            ['AAL', 'Anglo American'],
            ['ANTO', 'Antofagasta'],
            ['ARM', 'ARM Holdings'],
            ['ABF', 'Associated British Foods'],
            ['AZN', 'AstraZeneca'],
            ['AV', 'Aviva'],
            ['BAB', 'Babcock International Group'],
            ['BA', 'BAE Systems'],
            ['BARC', 'Barclays'],
            ['BG', 'BG Group'],
            ['BLT', 'BHP Billiton'],
            ['BP', 'BP'],
            ['BATS', 'British American Tobacco'],
            ['BLND', 'British Land Co'],
            ['BSY', 'British Sky Broadcasting Group'],
            ['BT.A', 'BT Group'],
            ['BNZL', 'Bunzl'],
            ['BRBY', 'Burberry Group'],
            ['CPI', 'Capita'],
            ['CSCG', 'Capital Shopping Centres Group'],
            ['CCL', 'Carnival'],
            ['CNA', 'Centrica'],
            ['CPG', 'Compass Group'],
            ['CRH', 'CRH'],
            ['CRDA', 'Croda International'],
            ['DGE', 'Diageo'],
            ['ENRC', 'Eurasian Natural Resources Corp.'],
            ['EVR', 'Evraz'],
            ['EXPN', 'Experian'],
            ['FRES', 'Fresnillo'],
            ['GFS', 'G4S'],
            ['GKN', 'GKN'],
            ['GSK', 'GlaxoSmithKline'],
            ['GLEN', 'Glencore International'],
            ['HMSO', 'Hammerson'],
            ['HL', 'Hargreaves Lansdown'],
            ['HSBA', 'HSBC Holdings'],
            ['IMI', 'IMI'],
            ['IMT', 'Imperial Tobacco Group'],
            ['IHG', 'InterContinental Hotels Group'],
            ['IAG', 'International Consolidated Airli..'],
            ['ITRK', 'Intertek Group'],
            ['ITV', 'ITV'],
            ['JMAT', 'Johnson Matthey'],
            ['KAZ', 'Kazakhmys'],
            ['KGF', 'Kingfisher'],
            ['LAND', 'Land Securities Group'],
            ['LGEN', 'Legal & General Group'],
            ['LLOY', 'Lloyds Banking Group'],
            ['MKS', 'Marks & Spencer Group'],
            ['MGGT', 'Meggitt'],
            ['MRO', 'Melrose Industries'],
            ['MRW', 'Morrison (Wm) Supermarkets'],
            ['NG', 'National Grid'],
            ['NXT', 'Next'],
            ['OML', 'Old Mutual'],
            ['PSON', 'Pearson'],
            ['PFC', 'Petrofac Ltd.'],
            ['POLY', 'Polymetal International'],
            ['PRU', 'Prudential'],
            ['RRS', 'Randgold Resources Ltd.'],
            ['RB', 'Reckitt Benckiser Group'],
            ['REL', 'Reed Elsevier'],
            ['RSL', 'Resolution Ltd.'],
            ['REX', 'Rexam'],
            ['RIO', 'Rio Tinto'],
            ['RR', 'Rolls-Royce Holdings'],
            ['RBS', 'Royal Bank of Scotland Group'],
            # ['RDSA', 'Royal Dutch Shell A'], # Doesn't seem to work...
            ['RDSB', 'Royal Dutch Shell B'],
            ['RSA', 'RSA Insurance Group'],
            ['SAB', 'SABMiller'],
            ['SGE', 'Sage Group'],
            ['SBRY', 'Sainsbury (J)'],
            ['SDR', 'Schroders'],
            ['SRP', 'Serco Group'],
            ['SVT', 'Severn Trent'],
            ['SHP', 'Shire Plc'],
            ['SN', 'Smith & Nephew'],
            ['SMIN', 'Smiths Group'],
            ['SSE', 'SSE'],
            ['STAN', 'Standard Chartered'],
            ['SL', 'Standard Life'],
            ['TATE', 'Tate & Lyle'],
            ['TSCO', 'Tesco'],
            ['TT', 'TUI Travel'],
            ['TLW', 'Tullow Oil'],
            ['ULVR', 'Unilever'],
            ['UU', 'United Utilities Group'],
            ['VED', 'Vedanta Resources'],
            ['VOD', 'Vodafone Group'],
            ['WEIR', 'Weir Group'],
            ['WTB', 'Whitbread'],
            ['WOS', 'Wolseley'],
            ['WG', 'Wood Group (John)'],
            ['WPP', 'WPP'],
            ['XTA', 'Xstrata']]